### ISSUE TITLE
Amend ErrorHandling JSON response decision logic

### ISSUE THREAD

**Issue by welshronaldo** [assureddt/pact#68]
As per documentation (highlighted):

![image](https://user-images.githubusercontent.com/3264267/113702326-47b04e00-96d1-11eb-83d0-2a3f4445cab0.png)

This hasn't been fully fine-tuned for Web API scenarios.  It's currently making the decision to return JSON based on the presence of the `X-Requested-With` header with the value `XMLHttpRequest` - with the origins being that it was only used in conjunction with AJAX requests.

Now that we're more commonly using it for general-purpose APIs, it's evident that this logic is not suitable for the API methods being called from Swagger/Postman or any other non-AJAX context (as they do not, by default, include that header, understandably), so this will need review.

Proposal: update logic to make decision based on value of `Accept` header containing the value `text/html` instead.  Would appreciate expanded perspective on this as it's based on my own usage currently.

Paging @jonny64bit for input.

**Comment by jonny64bit** [comment]
@welshronaldo just had a look what the fetch api is doing as this is really the future instead of ajax.

Sadly for the `Accept` its sending `Accept: */*` so this isn't going to work without us adding in a extra header option everywhere we use the fetch api.  

This is the default header on the request for the fetch api. Sadly very little to go on.

```
GET /cake/read?page=0&size=10&order=name&direction=0&filter= HTTP/2
Host: localhost:8222
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://localhost:8222/cake
Connection: keep-alive
Cookie: Anomed...
Pragma: no-cache
Cache-Control: no-cache
TE: Trailers
```

Is there anyway for us to presume server side rather then relying on whats being sent?

**Comment by welshronaldo** [comment]
Absolutely, yes, that's what I'm driving at above with `text/html` actually - we will only return HTML if the request specifies that in `Accept`, so exactly as you'd require there (effectively flipping the logic and assuming JSON unless HTML specified).  I'm not sure if there are any scenarios in which a web browser request would not include it, but you would think that would be very non-standard. Will take a look around to see if there's much further info on it but I expect that's the way to go. Cheers!

**Comment by jonny64bit** [comment]
@welshronaldo ahh yes sorry. Yep that would work.
